"""removetime

Revision ID: 29ae7e724333
Revises: f347f861c1f8
Create Date: 2025-06-16 04:43:54.718791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29ae7e724333'
down_revision = 'f347f861c1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
