"""edit

Revision ID: 3cf08c9924d9
Revises: 57dbabc3fab1
Create Date: 2025-06-13 10:56:52.731677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf08c9924d9'
down_revision = '57dbabc3fab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi_ssid', sa.String(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['student_id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_column('wifi_ssid')

    # ### end Alembic commands ###
