"""Initial migration

Revision ID: 57dbabc3fab1
Revises: 
Create Date: 2025-06-13 08:24:58.350409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57dbabc3fab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('face_encoding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('attendance_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=11), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_courses',
    sa.Column('student_id', sa.String(length=11), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('attendancelog',
    sa.Column('student_id', sa.String(length=11), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=11), nullable=False),
    sa.Column('connection_strength', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('marking_ip', sa.String(length=45), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('verification_method', sa.String(length=20), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('verification_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendancelog')
    op.drop_table('student_courses')
    op.drop_table('attendance_session')
    op.drop_table('course')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
