"""Make wifi_ssid not null

Revision ID: 837ac3695f20
Revises: 3cf08c9924d9
Create Date: 2025-06-13 11:01:00.388939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837ac3695f20'
down_revision = '3cf08c9924d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.alter_column('wifi_ssid',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.alter_column('wifi_ssid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
