"""Add wifi_session table

Revision ID: 8654c923402c
Revises: d16046643de1
Create Date: 2025-06-15 12:19:07.270976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8654c923402c'
down_revision = 'd16046643de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wifi_session',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=11), nullable=False),
    sa.Column('hall_id', sa.String(), nullable=True),
    sa.Column('wifi_ssid', sa.String(), nullable=False),
    sa.Column('teacher_ip', sa.String(length=45), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_session')
    # ### end Alembic commands ###
