"""454588

Revision ID: d16046643de1
Revises: fcd9892e4a17
Create Date: 2025-06-14 11:18:41.748735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd16046643de1'
down_revision = 'fcd9892e4a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('face_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
