"""Add multiple

Revision ID: e80d0637bb67
Revises: 8654c923402c
Create Date: 2025-06-15 13:31:52.475757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e80d0637bb67'
down_revision = '8654c923402c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encodings', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
        batch_op.drop_column('face_encodings')

    # ### end Alembic commands ###
