"""ip

Revision ID: f347f861c1f8
Revises: e80d0637bb67
Create Date: 2025-06-15 15:31:37.408840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f347f861c1f8'
down_revision = 'e80d0637bb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_session')
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_ip', sa.String(length=45), nullable=True))
        batch_op.drop_column('wifi_ssid')

    # Step 2: Fill existing rows with a dummy value (e.g., '0.0.0.0')
    op.execute("UPDATE attendance_session SET teacher_ip = '0.0.0.0' WHERE teacher_ip IS NULL")

    # Step 3: Alter the column to NOT NULL
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.alter_column('teacher_ip', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi_ssid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('teacher_ip')

    op.create_table('wifi_session',
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('hall_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wifi_ssid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('teacher_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], name=op.f('wifi_session_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('wifi_session_pkey'))
    )
    # ### end Alembic commands ###
